# Exercise 4.8 Grouping and Aggregating Variables

### Tasks within the lesson

In [6]:
## Importing required packages

import pandas as pd
import numpy as np
import os

In [7]:
## Importing the data file

path = r'/Users/balachandark/Desktop/Instacart Basket Analysis/02 Data'

ords_prods_merge = pd.read_pickle(os.path.join(path, 'Prepared Data', 'ords_prods_merged.pkl'))

df = ords_prods_merge[:1000000]

df.shape

(1000000, 16)

In [8]:
df.columns

Index(['order_id', 'user_id', 'evaluation_set', 'order_number',
       'orders_day_of_week', 'order_hour_of_day', 'days_since_prior_order',
       'product_id', 'add_to_cart_order', 'reordered', 'product_name',
       'aisle_id', 'department_id', 'prices', 'busiest_day',
       'busiest_period_of_day'],
      dtype='object')

In [9]:
df.head(10)

,order_id,user_id,evaluation_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,busiest_period_of_day
0,2539329.0,1.0,prior,1.0,2,8,NaN,196,1,0,Soda,77,7,9.0,Regularly busy,Average orders
1,2539329.0,1.0,prior,1.0,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Regularly busy,Average orders
2,2539329.0,1.0,prior,1.0,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Regularly busy,Average orders
3,2539329.0,1.0,prior,1.0,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Regularly busy,Average orders
4,2539329.0,1.0,prior,1.0,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Regularly busy,Average orders
5,2398795.0,1.0,prior,2.0,3,7,15.0,196,1,1,Soda,77,7,9.0,Least busy days,Average orders
6,2398795.0,1.0,prior,2.0,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,Least busy days,Average orders
7,2398795.0,1.0,prior,2.0,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,Least busy days,Average orders
8,2398795.0,1.0,prior,2.0,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,Least busy days,Average orders
9,2398795.0,1.0,prior,2.0,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,Least busy days,Average orders

In [10]:
## Using groupby function

df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

In [11]:
## Using groupby method 2

df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [12]:
## Using dot notation
df.groupby('department_id').order_number.mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [13]:
## Performing multiple aggregations

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean  min   max
department_id
1                14.800024  1.0  99.0
2                17.091743  1.0  98.0
3                17.913544  1.0  99.0
4                17.893092  1.0  99.0
5                15.214270  1.0  99.0
6                15.382135  1.0  99.0
7                17.694027  1.0  99.0
8                16.458105  1.0  91.0
9                15.957363  1.0  99.0
10               20.091818  1.0  99.0
11               16.482026  1.0  99.0
12               15.615061  1.0  99.0
13               16.484023  1.0  99.0
14               17.524632  1.0  99.0
15               15.691875  1.0  99.0
16               18.014071  1.0  99.0
17               16.150593  1.0  99.0
18               19.602850  1.0  99.0
19               17.631340  1.0  99.0
20               17.138607  1.0  99.0
21               21.956893  1.0  97.0

In [14]:
## Using transform function to flag loyal customers

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [15]:
ords_prods_merge.head(100)

,order_id,user_id,evaluation_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,busiest_period_of_day,max_order
0,2539329.0,1.0,prior,1.0,2,8,NaN,196,1,0,Soda,77,7,9.0,Regularly busy,Average orders,10.0
1,2539329.0,1.0,prior,1.0,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Regularly busy,Average orders,10.0
2,2539329.0,1.0,prior,1.0,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Regularly busy,Average orders,10.0
3,2539329.0,1.0,prior,1.0,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Regularly busy,Average orders,10.0
4,2539329.0,1.0,prior,1.0,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Regularly busy,Average orders,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,738281.0,2.0,prior,4.0,2,10,8.0,21150,13,0,Fire Grilled Steak Bowl,38,1,5.9,Regularly busy,Most orders,14.0
96,1673511.0,2.0,prior,5.0,3,11,8.0,47144,1,0,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,Least busy days,Most orders,14.0
97,1673511.0,2.0,prior,5.0,3,11,8.0,5322,2,0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,Least busy days,Most orders,14.0
98,1673511.0,2.0,prior,5.0,3,11,8.0,17224,3,0,Oats & Honey Gluten Free Granola,3,19,1.6,Least busy days,Most orders,14.0
99,1673511.0,2.0,prior,5.0,3,11,8.0,38656,4,0,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,Least busy days,Most orders,14.0

In [16]:
## Change the table displaying method

pd.options.display.max_rows = None

In [17]:
ords_prods_merge.head(100)

,order_id,user_id,evaluation_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,busiest_period_of_day,max_order
0,2539329.0,1.0,prior,1.0,2,8,NaN,196,1,0,Soda,77,7,9.0,Regularly busy,Average orders,10.0
1,2539329.0,1.0,prior,1.0,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Regularly busy,Average orders,10.0
2,2539329.0,1.0,prior,1.0,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Regularly busy,Average orders,10.0
3,2539329.0,1.0,prior,1.0,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Regularly busy,Average orders,10.0
4,2539329.0,1.0,prior,1.0,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Regularly busy,Average orders,10.0
5,2398795.0,1.0,prior,2.0,3,7,15.0,196,1,1,Soda,77,7,9.0,Least busy days,Average orders,10.0
6,2398795.0,1.0,prior,2.0,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,Least busy days,Average orders,10.0
7,2398795.0,1.0,prior,2.0,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,Least busy days,Average orders,10.0
8,2398795.0,1.0,prior,2.0,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,Least busy days,Average orders,10.0
9,2398795.0,1.0,prior,2.0,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,Least busy days,Average orders,10.0
10,2398795.0,1.0,prior,2.0,3,7,15.0,13032,6,0,Cinnamon Toast Crunch,121,14,4.0,Least busy days,Average orders,10.0
11,473747.0,1.0,prior,3.0,3,12,21.0,196,1,1,Soda,77,7,9.0,Least busy days,Most orders,10.0
12,473747.0,1.0,prior,3.0,3,12,21.0,12427,2,1,Original Beef Jerky,23,19,4.4,Least busy days,Most orders,10.0
13,473747.0,1.0,prior,3.0,3,12,21.0,10258,3,1,Pistachios,117,19,3.0,Least busy days,Most orders,10.0
14,473747.0,1.0,prior,3.0,3,12,21.0,25133,4,0,Organic String Cheese,21,16,8.6,Least busy days,Most orders,10.0
15,473747.0,1.0,prior,3.0,3,12,21.0,30450,5,0,Creamy Almond Butter,88,13,3.2,Least busy days,Most orders,10.0
16,2254736.0,1.0,prior,4.0,4,7,29.0,196,1,1,Soda,77,7,9.0,Least busy days,Average orders,10.0
17,2254736.0,1.0,prior,4.0,4,7,29.0,12427,2,1,Original Beef Jerky,23,19,4.4,Least busy days,Average orders,10.0
18,2254736.0,1.0,prior,4.0,4,7,29.0,10258,3,1,Pistachios,117,19,3.0,Least busy days,Average orders,10.0
19,2254736.0,1.0,prior,4.0,4,7,29.0,25133,4,1,Organic String Cheese,21,16,8.6,Least busy days,Average orders,10.0
20,2254736.0,1.0,prior,4.0,4,7,29.0,26405,5,1,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Least busy days,Average orders,10.0
21,431534.0,1.0,prior,5.0,4,15,28.0,196,1,1,Soda,77,7,9.0,Least busy days,Most orders,10.0
22,431534.0,1.0,prior,5.0,4,15,28.0,12427,2,1,Original Beef Jerky,23,19,4.4,Least busy days,Most orders,10.0
23,431534.0,1.0,prior,5.0,4,15,28.0,10258,3,1,Pistachios,117,19,3.0,Least busy days,Most orders,10.0
24,431534.0,1.0,prior,5.0,4,15,28.0,25133,4,1,Organic String Cheese,21,16,8.6,Least busy days,Most orders,10.0
25,431534.0,1.0,prior,5.0,4,15,28.0,10326,5,0,Organic Fuji Apples,24,4,2.7,Least busy days,Most orders,10.0
26,431534.0,1.0,prior,5.0,4,15,28.0,17122,6,0,Honeycrisp Apples,24,4,14.0,Least busy days,Most orders,10.0
27,431534.0,1.0,prior,5.0,4,15,28.0,41787,7,0,Bartlett Pears,24,4,5.0,Least busy days,Most orders,10.0
28,431534.0,1.0,prior,5.0,4,15,28.0,13176,8,1,Bag of Organic Bananas,24,4,10.3,Least busy days,Most orders,10.0
29,3367565.0,1.0,prior,6.0,2,7,19.0,196,1,1,Soda,77,7,9.0,Regularly busy,Average orders,10.0
30,3367565.0,1.0,prior,6.0,2,7,19.0,12427,2,1,Original Beef Jerky,23,19,4.4,Regularly busy,Average orders,10.0
31,3367565.0,1.0,prior,6.0,2,7,19.0,10258,3,1,Pistachios,117,19,3.0,Regularly busy,Average orders,10.0
32,3367565.0,1.0,prior,6.0,2,7,19.0,25133,4,1,Organic String Cheese,21,16,8.6,Regularly busy,Average orders,10.0
33,550135.0,1.0,prior,7.0,1,9,20.0,196,1,1,Soda,77,7,9.0,Busiest days,Average orders,10.0
34,550135.0,1.0,prior,7.0,1,9,20.0,10258,2,1,Pistachios,117,19,3.0,Busiest days,Average orders,10.0
35,550135.0,1.0,prior,7.0,1,9,20.0,12427,3,1,Original Beef Jerky,23,19,4.4,Busiest days,Average orders,10.0
36,550135.0,1.0,prior,7.0,1,9,20.0,25133,4,1,Organic String Cheese,21,16,8.6,Busiest days,Average orders,10.0
37,550135.0,1.0,prior,7.0,1,9,20.0,13032,5,1,Cinnamon Toast Crunch,121,14,4.0,Busiest days,Average orders,10.0
38,3108588.0,1.0,prior,8.0,1,14,14.0,12427,1,1,Original Beef Jerky,23,19,4.4,Busiest days,Most orders,10.0
39,3108588.0,1.0,prior,8.0,1,14,14.0,196,2,1,Soda,77,7,9.0,Busiest days,Most orders,10.0
40,3108588.0,1.0,prior,8.0,1,14,14.0,10258,3,1,Pistachios,117,19,3.0,Busiest days,Most orders,10.0
41,3108588.0,1.0,prior,8.0,1,14,14.0,25133,4,1,Organic String Cheese,21,16,8.6,Busiest days,Most orders,10.0
42,3108588.0,1.0,prior,8.0,1,14,14.0,46149,5,0,Zero Calorie Cola,77,7,13.4,Busiest days,Most orders,10.0
43,3108588.0,1.0,prior,8.0,1,14,14.0,49235,6,0,Organic Half & Half,53,16,1.8,Busiest days,Most orders,10.0
44,2295261.0,1.0,prior,9.0,1,16,0.0,49235,1,1,Organic Half & Half,53,16,1.8,Busiest days,Most orders,10.0
45,2295261.0,1.0,prior,9.0,1,16,0.0,46149,2,1,Zero Calorie Cola,77,7,13.4,Busiest days,Most orders,10.0
46,2295261.0,1.0,prior,9.0,1,16,0.0,25133,3,1,Organic String Cheese,21,16,8.6,Busiest days,Most orders,10.0
47,2295261.0,1.0,prior,9.0,1,16,0.0,196,4,1,Soda,77,7,9.0,Busiest days,Most orders,10.0
48,2295261.0,1.0,prior,9.0,1,16,0.0,10258,5,1,Pistachios,117,19,3.0,Busiest days,Most orders,10.0
49,2295261.0,1.0,prior,9.0,1,16,0.0,12427,6,1,Original Beef Jerky,23,19,4.4,Busiest days,Most orders,10.0
50,2550362.0,1.0,prior,10.0,4,8,30.0,196,1,1,Soda,77,7,9.0,Least busy days,Average orders,10.0
51,2550362.0,1.0,prior,10.0,4,8,30.0,46149,2,1,Zero Calorie Cola,77,7,13.4,Least busy days,Average orders,10.0
52,2550362.0,1.0,prior,10.0,4,8,30.0,39657,3,0,Milk Chocolate Almonds,45,19,6.8,Least busy days,Average orders,10.0
53,2550362.0,1.0,prior,10.0,4,8,30.0,38928,4,0,0% Greek Strained Yogurt,120,16,12.6,Least busy days,Average orders,10.0
54,2550362.0,1.0,prior,10.0,4,8,30.0,25133,5,1,Organic String Cheese,21,16,8.6,Least busy days,Average orders,10.0
55,2550362.0,1.0,prior,10.0,4,8,30.0,10258,6,1,Pistachios,117,19,3.0,Least busy days,Average orders,10.0
56,2550362.0,1.0,prior,10.0,4,8,30.0,35951,7,0,Organic Unsweetened Almond Milk,91,16,1.3,Least busy days,Average orders,10.0
57,2550362.0,1.0,prior,10.0,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,121,14,4.0,Least busy days,Average orders,10.0
58,2550362.0,1.0,prior,10.0,4,8,30.0,12427,9,1,Original Beef Jerky,23,19,4.4,Least busy days,Average orders,10.0
59,2168274.0,2.0,prior,1.0,2,11,NaN,32792,1,0,Chipotle Beef & Pork Realstick,23,19,5.2,Regularly busy,Most orders,14.0
60,2168274.0,2.0,prior,1.0,2,11,NaN,47766,2,0,Organic Avocado,24,4,6.3,Regularly busy,Most orders,14.0
61,2168274.0,2.0,prior,1.0,2,11,NaN,20574,3,0,Roasted Turkey,96,20,2.3,Regularly busy,Most orders,14.0
62,2168274.0,2.0,prior,1.0,2,11,NaN,12000,4,0,Baked Organic Sea Salt Crunchy Pea Snack,72,13,10.9,Regularly busy,Most orders,14.0
63,2168274.0,2.0,prior,1.0,2,11,NaN,48110,5,0,Thin Stackers Brown Rice Lightly Salted,78,19,2.7,Regularly busy,Most orders,14.0
64,2168274.0,2.0,prior,1.0,2,11,NaN,22474,6,0,Cheddar Bunnies Snack Crackers,78,19,4.1,Regularly busy,Most orders,14.0
65,2168274.0,2.0,prior,1.0,2,11,NaN,16589,7,0,Plantain Chips,107,19,5.0,Regularly busy,Most orders,14.0
66,2168274.0,2.0,prior,1.0,2,11,NaN,35917,8,0,Organic Just Concord Grape Juice,98,7,9.4,Regularly busy,Most orders,14.0
67,2168274.0,2.0,prior,1.0,2,11,NaN,27344,9,0,Uncured Genoa Salami,96,20,14.8,Regularly busy,Most orders,14.0
68,2168274.0,2.0,prior,1.0,2,11,NaN,30489,10,0,Original Hummus,67,20,7.5,Regularly busy,Most orders,14.0
69,2168274.0,2.0,prior,1.0,2,11,NaN,27966,11,0,Organic Raspberries,123,4,4.4,Regularly busy,Most orders,14.0
70,2168274.0,2.0,prior,1.0,2,11,NaN,13176,12,0,Bag of Organic Bananas,24,4,10.3,Regularly busy,Most orders,14.0
71,2168274.0,2.0,prior,1.0,2,11,NaN,45066,13,0,Honeycrisp Apple,24,4,2.5,Regularly busy,Most orders,14.0
72,1501582.0,2.0,prior,2.0,5,10,10.0,16797,1,0,Strawberries,24,4,1.3,Regularly busy,Most orders,14.0
73,1501582.0,2.0,prior,2.0,5,10,10.0,47526,2,0,Goat Cheese Log,21,16,2.0,Regularly busy,Most orders,14.0
74,1501582.0,2.0,prior,2.0,5,10,10.0,8479,3,0,Original Black Box Tablewater Cracker,78,19,3.5,Regularly busy,Most orders,14.0
75,1501582.0,2.0,prior,2.0,5,10,10.0,47766,4,1,Organic Avocado,24,4,6.3,Regularly busy,Most orders,14.0
76,1501582.0,2.0,prior,2.0,5,10,10.0,19051,5,0,"Pita Chips, Simply Naked, Party Size",107,19,3.9,Regularly busy,Most orders,14.0
77,1501582.0,2.0,prior,2.0,5,10,10.0,8138,6,0,Traditional Hummus,67,20,2.0,Regularly busy,Most orders,14.0
78,1901567.0,2.0,prior,3.0,1,10,3.0,47766,1,1,Organic Avocado,24,4,6.3,Busiest days,Most orders,14.0
79,1901567.0,2.0,prior,3.0,1,10,3.0,32792,2,1,Chipotle Beef & Pork Realstick,23,19,5.2,Busiest days,Most orders,14.0
80,1901567.0,2.0,prior,3.0,1,10,3.0,20574,3,1,Roasted Turkey,96,20,2.3,Busiest days,Most orders,14.0
81,1901567.0,2.0,prior,3.0,1,10,3.0,7781,4,0,Organic Sticks Low Moisture Part Skim Mozzarel...,21,16,6.6,Busiest days,Most orders,14.0
82,1901567.0,2.0,prior,3.0,1,10,3.0,28874,5,0,Carrot Ginger Soup,1,20,6.2,Busiest days,Most orders,14.0
83,738281.0,2.0,prior,4.0,2,10,8.0,49451,1,0,Artichoke Spinach Dip,67,20,7.1,Regularly busy,Most orders,14.0
84,738281.0,2.0,prior,4.0,2,10,8.0,32792,2,1,Chipotle Beef & Pork Realstick,23,19,5.2,Regularly busy,Most orders,14.0
85,738281.0,2.0,prior,4.0,2,10,8.0,32139,3,0,Hommus Classic Original,67,20,7.5,Regularly busy,Most orders,14.0
86,738281.0,2.0,prior,4.0,2,10,8.0,34688,4,0,Good Belly Probiotics Juice Drink Blueberry Ac...,31,7,5.8,Regularly busy,Most orders,14.0
87,738281.0,2.0,prior,4.0,2,10,8.0,36735,5,0,Organic Roasted Sliced Chicken Breast,96,20,8.9,Regularly busy,Most orders,14.0
88,738281.0,2.0,prior,4.0,2,10,8.0,37646,6,0,Organic Gala Apples,24,4,9.1,Regularly busy,Most orders,14.0
89,738281.0,2.0,prior,4.0,2,10,8.0,22829,7,0,Multigrain Flax Seeded Flatbread Crackers,78,19,5.5,Regularly busy,Most orders,14.0
90,738281.0,2.0,prior,4.0,2,10,8.0,24852,8,0,Banana,24,4,12.3,Regularly busy,Most orders,14.0
91,738281.0,2.0,prior,4.0,2,10,8.0,47209,9,0,Organic Hass Avocado,24,4,4.0,Regularly busy,Most orders,14.0
92,738281.0,2.0,prior,4.0,2,10,8.0,33276,10,0,Kalamata Olive Spread,67,20,10.8,Regularly busy,Most orders,14.0
93,738281.0,2.0,prior,4.0,2,10,8.0,45613,11,0,Pad Thai,38,1,12.6,Regularly busy,Most orders,14.0
94,738281.0,2.0,prior,4.0,2,10,8.0,9681,12,0,Chicken Tikka Masala with Cumin Infused Basmat...,38,1,2.0,Regularly busy,Most orders,14.0
95,738281.0,2.0,prior,4.0,2,10,8.0,21150,13,0,Fire Grilled Steak Bowl,38,1,5.9,Regularly busy,Most orders,14.0
96,1673511.0,2.0,prior,5.0,3,11,8.0,47144,1,0,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,Least busy days,Most orders,14.0
97,1673511.0,2.0,prior,5.0,3,11,8.0,5322,2,0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,Least busy days,Most orders,14.0
98,1673511.0,2.0,prior,5.0,3,11,8.0,17224,3,0,Oats & Honey Gluten Free Granola,3,19,1.6,Least busy days,Most orders,14.0
99,1673511.0,2.0,prior,5.0,3,11,8.0,38656,4,0,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,Least busy days,Most orders,14.0

In [18]:
## Deriving columns with loc() 

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [19]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [20]:
## Checking the columns
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       1.0      New customer           1.0
1       1.0      New customer           1.0
2       1.0      New customer           1.0
3       1.0      New customer           1.0
4       1.0      New customer           1.0
5       1.0      New customer           2.0
6       1.0      New customer           2.0
7       1.0      New customer           2.0
8       1.0      New customer           2.0
9       1.0      New customer           2.0
10      1.0      New customer           2.0
11      1.0      New customer           3.0
12      1.0      New customer           3.0
13      1.0      New customer           3.0
14      1.0      New customer           3.0
15      1.0      New customer           3.0
16      1.0      New customer           4.0
17      1.0      New customer           4.0
18      1.0      New customer           4.0
19      1.0      New customer           4.0
20      1.0      New customer           4.0
21      1.0      New customer           5.0
22      1.0      New customer           5.0
23      1.0      New customer           5.0
24      1.0      New customer           5.0
25      1.0      New customer           5.0
26      1.0      New customer           5.0
27      1.0      New customer           5.0
28      1.0      New customer           5.0
29      1.0      New customer           6.0
30      1.0      New customer           6.0
31      1.0      New customer           6.0
32      1.0      New customer           6.0
33      1.0      New customer           7.0
34      1.0      New customer           7.0
35      1.0      New customer           7.0
36      1.0      New customer           7.0
37      1.0      New customer           7.0
38      1.0      New customer           8.0
39      1.0      New customer           8.0
40      1.0      New customer           8.0
41      1.0      New customer           8.0
42      1.0      New customer           8.0
43      1.0      New customer           8.0
44      1.0      New customer           9.0
45      1.0      New customer           9.0
46      1.0      New customer           9.0
47      1.0      New customer           9.0
48      1.0      New customer           9.0
49      1.0      New customer           9.0
50      1.0      New customer          10.0
51      1.0      New customer          10.0
52      1.0      New customer          10.0
53      1.0      New customer          10.0
54      1.0      New customer          10.0
55      1.0      New customer          10.0
56      1.0      New customer          10.0
57      1.0      New customer          10.0
58      1.0      New customer          10.0
59      2.0  Regular customer           1.0

### Task for Exercise 4.8

#### Question 4.8.2 & 4.8.3

In [23]:
## Find the mean of order number and department id for the whole data frame

ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

##### The values of the subset is close to the values of the whole data frame. The sample size quite large enough to get closer to the population values.

#### Question 4.8.4

In [26]:
## Apply transform function

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

## Checking the data frame

ords_prods_merge.head(10)

,order_id,user_id,evaluation_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,busiest_period_of_day,max_order,loyalty_flag
0,2539329.0,1.0,prior,1.0,2,8,NaN,196,1,0,Soda,77,7,9.0,Regularly busy,Average orders,10.0,New customer
1,2539329.0,1.0,prior,1.0,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Regularly busy,Average orders,10.0,New customer
2,2539329.0,1.0,prior,1.0,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Regularly busy,Average orders,10.0,New customer
3,2539329.0,1.0,prior,1.0,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Regularly busy,Average orders,10.0,New customer
4,2539329.0,1.0,prior,1.0,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Regularly busy,Average orders,10.0,New customer
5,2398795.0,1.0,prior,2.0,3,7,15.0,196,1,1,Soda,77,7,9.0,Least busy days,Average orders,10.0,New customer
6,2398795.0,1.0,prior,2.0,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,Least busy days,Average orders,10.0,New customer
7,2398795.0,1.0,prior,2.0,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,Least busy days,Average orders,10.0,New customer
8,2398795.0,1.0,prior,2.0,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,Least busy days,Average orders,10.0,New customer
9,2398795.0,1.0,prior,2.0,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,Least busy days,Average orders,10.0,New customer

In [27]:
## Using loyalty flag to find the avearge prices of the purchased products

ords_prods_merge.groupby('loyalty_flag')['prices'].mean()

loyalty_flag
Loyal customer      10.386336
New customer        13.294670
Regular customer    12.495717
Name: prices, dtype: float64

##### It appears that the loyal customers have purchased the products multiple times. However, the order value of the products are lesser compared to the new and regular customers

#### Question 4.8.6

In [30]:
## Creating spending flag for each user based on the average price

ords_prods_merge['spending_behavior'] = ords_prods_merge.groupby('user_id')['prices'].transform('mean')

In [31]:
## Creating the spending flag using .loc function

ords_prods_merge.loc[ords_prods_merge['spending_behavior'] >= 10, 'spending_flag'] = 'High spender'
ords_prods_merge.loc[ords_prods_merge['spending_behavior'] < 10, 'spending_flag'] = 'Low spender'

In [32]:
ords_prods_merge.head()

,order_id,user_id,evaluation_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,busiest_period_of_day,max_order,loyalty_flag,spending_behavior,spending_flag
0,2539329.0,1.0,prior,1.0,2,8,NaN,196,1,0,Soda,77,7,9.0,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender
1,2539329.0,1.0,prior,1.0,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender
2,2539329.0,1.0,prior,1.0,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender
3,2539329.0,1.0,prior,1.0,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender
4,2539329.0,1.0,prior,1.0,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender

#### Question 4.8.7

In [34]:
## Creating order frequency flag

ords_prods_merge['order_frequent'] = ords_prods_merge.groupby('user_id')['days_since_prior_order'].transform('median')

In [35]:
ords_prods_merge.loc[ords_prods_merge['order_frequent'] > 20, 'order_freq_flag'] = 'Non-frequent customer'
ords_prods_merge.loc[(ords_prods_merge['order_frequent'] > 10) & (ords_prods_merge['order_frequent'] <= 20), 'order_freq_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['order_frequent'] <= 10, 'order_freq_flag'] = 'Frequent customer'

In [36]:
## Checking the columns

ords_prods_merge.head()

,order_id,user_id,evaluation_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,department_id,prices,busiest_day,busiest_period_of_day,max_order,loyalty_flag,spending_behavior,spending_flag,order_frequent,order_freq_flag
0,2539329.0,1.0,prior,1.0,2,8,NaN,196,1,0,...,7,9.0,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329.0,1.0,prior,1.0,2,8,NaN,14084,2,0,...,16,12.5,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329.0,1.0,prior,1.0,2,8,NaN,12427,3,0,...,19,4.4,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329.0,1.0,prior,1.0,2,8,NaN,26088,4,0,...,19,4.7,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329.0,1.0,prior,1.0,2,8,NaN,26405,5,0,...,17,1.0,Regularly busy,Average orders,10.0,New customer,6.367797,Low spender,20.5,Non-frequent customer

#### Question 4.8.9

In [38]:
## Exporting the data frame

ords_prods_merge.to_pickle(os.path.join(path, 'Prepared Data', 'ords_prods_merge_4.8.pkl'))

<center><b> End of Report </b></center>